[project]
name = "dpsn-jax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flax>=0.12.2",
    "grain>=0.2.15",
    "jax[cpu]>=0.8.2",
    "optax>=0.2.6",
]
